-- ============================================================================
-- R5.3: Insert the clean-room item bank and skill taxonomy as a NEW diagnostic.
-- New rows only. No existing diagnostics / diagnostic_questions / skills row is
-- modified or deleted, so old pilot sessions keep rendering (their sessions,
-- results and foerderplaene still point at the legacy diagnostic row
-- 00000000-0000-0000-0000-000000000001 via their own diagnostic_id).
--
-- DESIGN (docs/clean-room/02-blueprint.md, two-tier):
--   * Core tier:  60 items across Domains A-D (question_count = 60).
--   * Deep-dive:  32 optional per-domain items. They live in the SAME diagnostic
--     and same table, distinguished by a new `tier` column ('core' | 'deepdive'),
--     with question_number continuing at 61..92. Explicit `tier` is preferred
--     over implicit numbering so dashboard / edge functions can filter on it.
--   * `diagnostics.question_count` counts the core tier (60), matching the
--     default administration length. `diagnostic-results` completion logic is
--     addressed separately in R5.4.
--
-- SLUG / IDs: new diagnostic uses slug 'cleanroom-v1', version 1, fixed uuid
-- 00000000-0000-0000-0000-000000000002 (legacy row keeps ...0001).
--
-- SKILL TAXONOMY: the legacy `skills` table (id, category, color, card_number,
-- title_de, title_en, description_de, description_en) predates the new
-- taxonomy (skill_id, domain, construct_id, color, title_de, title_en,
-- description_de, description_en). We add nullable `domain` and `construct_id`
-- columns (IF NOT EXISTS) and backfill them for the 36 new rows. `card_number`
-- is NOT NULL in the legacy schema but the new taxonomy drops it -> insert 0.
-- Legacy skill rows keep their values (domain/construct_id stay NULL for them).
-- All inserts are idempotent (ON CONFLICT DO NOTHING) so re-runs never touch
-- existing rows.
-- ============================================================================

-- New taxonomy metadata columns on the legacy skills table (nullable; legacy
-- rows are not backfilled so they remain untouched).
alter table public.skills
  add column if not exists domain text,
  add column if not exists construct_id text;

insert into public.skills (id, category, color, card_number, title_de, title_en,
  description_de, description_en, domain, construct_id) values
  ('A1.1a', 'Domäne A', 'amber', 0, 'Vorwärtszählen bis 20', 'Counting forward to 20', 'Das Kind zählt von einem beliebigen Startpunkt im Zahlenraum bis 20 fehlerfrei vorwärts weiter und beendet die Zählfolge zuverlässig. Es verliert auch dann nicht den Faden, wenn es mitten in der Reihe beginnt.', 'The child counts forward from any starting point up to 20 without errors and completes the counting sequence reliably. Starting in the middle of the series does not unsettle the child.', 'A', 'A1.1'),
  ('A1.1b', 'Domäne A', 'amber', 0, 'Vorwärtszählen bis 100', 'Counting forward to 100', 'Das Kind setzt das Vorwärtszählen von beliebigen Startpunkten über die Zehnergrenzen hinweg bis in den Hunderterraum fort. Die Zahlenfolge bleibt dabei auch über mehrere Stellenwechsel hinweg stabil.', 'The child continues counting forward from any starting point across the tens boundaries up to one hundred. The sequence stays stable even across several place-value changes.', 'A', 'A1.1'),
  ('A1.2a', 'Domäne A', 'amber', 0, 'Rückwärtszählen bis 20', 'Counting backward to 20', 'Das Kind zählt von einem beliebigen Startpunkt aus abwärts bis in den Bereich der kleinen Zahlen, ohne die Folge zu unterbrechen. Der Wechsel von einer Zahl zur nächstkleineren gelingt sicher.', 'The child counts downward from any starting point into the small-number range without breaking the sequence. Moving from one number to the next lower one is done reliably.', 'A', 'A1.2'),
  ('A1.2b', 'Domäne A', 'amber', 0, 'Rückwärtszählen bis 100', 'Counting backward to 100', 'Das Kind zählt von Startpunkten im Hunderterraum aus rückwärts und überschreitet dabei die Zehnergrenzen korrekt. Die absteigende Folge gelingt auch über mehrere Stellenwechsel hinweg ohne Abweichung.', 'The child counts backward from starting points in the hundreds range, crossing the tens boundaries correctly. The descending sequence stays correct even across several place-value changes.', 'A', 'A1.2'),
  ('A1.3', 'Domäne A', 'amber', 0, 'Zählen in Schritten', 'Counting in steps', 'Das Kind zählt in gleichbleibenden Schritten von zwei, fünf und zehn sowohl vorwärts als auch rückwärts. Es nutzt dabei die rhythmische Struktur der Zahlenreihe und behält das Schrittmaß bei.', 'The child counts forward and backward in constant steps of two, five and ten. It uses the rhythmic structure of the number sequence and keeps the step size steady.', 'A', 'A1.3'),
  ('A1.4', 'Domäne A', 'amber', 0, 'Vorgänger und Nachfolger bestimmen', 'Determining predecessor and successor', 'Das Kind nennt zu einer Zahl ihren unmittelbaren Vorgänger und Nachfolger und belegt damit eine sichere Vorstellung von der Anordnung der Zahlen. Die Aufgabe gelingt auch an Zehnergrenzen wie unmittelbar vor und nach einer vollen Zehn.', 'The child names the immediate predecessor and successor of a number, showing a secure grasp of how numbers are ordered. This also works at tens boundaries, such as directly before and after a full ten.', 'A', 'A1.4'),
  ('A1.5', 'Domäne A', 'amber', 0, 'Zählen über den Zehnerübergang', 'Counting across the tens boundary', 'Das Kind zählt flüssig über eine Zehnergrenze hinweg, zum Beispiel von 17 bis 23, ohne an der Übergangsstelle zu stocken. Die Überschreitung der vollen Zehn verläuft ohne Fehler und ohne Pause.', 'The child counts fluently across a tens boundary, for example from 17 to 23, without hesitating at the crossing point. Passing a full ten happens without errors and without a pause.', 'A', 'A1.5'),
  ('A2.1', 'Domäne A', 'amber', 0, 'Mengen auf einen Blick erfassen', 'Recognizing quantities at a glance', 'Das Kind erkennt kleine Mengen bis etwa vier oder fünf sofort und sicher, ohne sie einzeln abzuzählen. Die Anzahl wird direkt aus dem Gesamteindruck entnommen.', 'The child recognizes small quantities up to about four or five immediately and reliably, without counting them one by one. The number is read directly from the overall impression.', 'A', 'A2.1'),
  ('A2.2', 'Domäne A', 'amber', 0, 'Mengen über Strukturen erkennen', 'Recognizing quantities through structures', 'Das Kind erfasst Mengen bis zehn über bekannte Anordnungen wie Fünfergruppen, Zweiergruppen oder Zehnerfelder. Bekannte Muster werden genutzt, um die Anzahl ohne langes Abzählen zu bestimmen.', 'The child grasps quantities up to ten through familiar arrangements such as groups of five, groups of two or ten-frames. Known patterns are used to determine the number without prolonged counting.', 'A', 'A2.2'),
  ('A2.3', 'Domäne A', 'amber', 0, 'Mengen vergleichen', 'Comparing quantities', 'Das Kind vergleicht zwei Mengen und entscheidet zuverlässig, welche größer und welche kleiner ist. Der Vergleich gelingt direkt über die Mengen selbst, ohne vorheriges Abzählen beider Mengen.', 'The child compares two quantities and decides reliably which is larger and which is smaller. The comparison works directly on the quantities, without counting both first.', 'A', 'A2.3'),
  ('A3.1', 'Domäne A', 'amber', 0, 'Zahlen aus Teilen zusammensetzen', 'Composing numbers from parts', 'Das Kind versteht eine Zahl bis zehn als Zusammensetzung aus zwei Teilen und kann beide Richtungen der Zerlegung anwenden. Aus zwei bekannten Teilen wird das Ganze, aus dem Ganzen werden die Teile bestimmt.', 'The child understands a number up to ten as a composition of two parts and can apply both directions of decomposition. Two known parts give the whole, and the whole gives its parts.', 'A', 'A3.1'),
  ('A3.2', 'Domäne A', 'amber', 0, 'Zerlegungen einer Zahl finden', 'Finding decompositions of a number', 'Das Kind findet zu einer Zahl mehrere unterschiedliche Zerlegungen und wechselt sicher zwischen verschiedenen Zusammensetzungen derselben Zahl. Dabei nutzt es die Einsicht, dass eine Zahl auf viele Arten in Teile geteilt werden kann.', 'The child finds several different decompositions of a number and moves confidently between various combinations of the same number. It draws on the insight that a number can be split into parts in many ways.', 'A', 'A3.2'),
  ('A3.3', 'Domäne A', 'amber', 0, 'Zahlbeziehungen nutzen', 'Using number relationships', 'Das Kind verbindet Zahlen über Verdopplungen, Halbierungen und Nachbarzahlen miteinander. Aus bekannten Beziehungen leitet es unbekannte Ergebnisse ab und verankert Zahlen in einem Netz aus Zusammenhängen.', 'The child connects numbers through doubles, halves and neighbouring numbers. From known relationships it derives unknown results and anchors numbers in a network of connections.', 'A', 'A3.3'),
  ('B1.1', 'Domäne B', 'indigo', 0, 'Zehner und Einer erkennen', 'Recognizing tens and ones', 'Das Kind erkennt in einer zweistelligen Zahl die Zehner und die Einer und benennt ihre Anzahl. Es verbindet die geschriebene Zahl sicher mit ihrer Zusammensetzung aus Zehner- und Eineranteil.', 'The child recognizes the tens and the ones in a two-digit number and names how many there are. It reliably links the written number to its composition of tens and ones.', 'B', 'B1.1'),
  ('B1.2', 'Domäne B', 'indigo', 0, 'Einzelstücke zu Zehnern bündeln', 'Bundling single objects into tens', 'Das Kind fasst einzelne Objekte zu Zehnern zusammen und liest aus der Anzahl der Bündel und der übrig bleibenden Stücke die dargestellte Zahl ab. Das Bündeln wird als Veranschaulichung des Stellenwerts genutzt.', 'The child groups single objects into tens and reads the number shown from the count of bundles and remaining pieces. Bundling is used as a concrete illustration of place value.', 'B', 'B1.2'),
  ('B1.3', 'Domäne B', 'indigo', 0, 'Einen Zehner in Einer tauschen', 'Exchanging one ten for ones', 'Das Kind tauscht einen Zehner gegen zehn Einer und stellt damit eine Zahl in aufgelöster Form dar. Das Entbündeln gelingt auch dann, wenn die Darstellung der Zahl anschließend neu zusammengesetzt werden muss.', 'The child exchanges one ten for ten ones and represents a number in unbundled form. The unbundling also works when the number''s representation must then be reassembled.', 'B', 'B1.3'),
  ('B2.1', 'Domäne B', 'indigo', 0, 'Zahlen in der Stellenwerttafel darstellen', 'Representing numbers in a place-value table', 'Das Kind schreibt Zahlen in der Stellenwerttafel und in der Standardform und liest sie aus der Tafel richtig ab. Die Zuordnung von Ziffern zu Zehner- und Einerspalte gelingt sicher, auch wenn eine Spalte leer bleibt.', 'The child writes numbers in the place-value table and in standard form and reads them back correctly. Assigning digits to the tens and ones columns works reliably, even when one column stays empty.', 'B', 'B2.1'),
  ('B2.2', 'Domäne B', 'indigo', 0, 'Zahlen am Zahlenstrahl verorten', 'Placing numbers on the number line', 'Das Kind trägt Zahlen auf dem Zahlenstrahl ein und entnimmt ihnen ihre Lage im Zahlenraum. Es nutzt den Strahl als strukturiertes Modell, um Abstände und Anordnungen von Zahlen abzulesen.', 'The child places numbers on the number line and reads off their position in the number range. It uses the line as a structured model to read distances and the order of numbers.', 'B', 'B2.2'),
  ('B2.3', 'Domäne B', 'indigo', 0, 'Zahlen in ungewohnter Schreibweise lesen', 'Reading numbers in non-standard notation', 'Das Kind liest Zahlen in nicht-standardisierter Schreibweise wie „1 Z + 14 E" und erkennt, dass dieselbe Zahl auf verschiedene Weisen gebündelt sein kann. Es überführt solche Darstellungen sicher in die Standardform.', 'The child reads numbers written in a non-standard way, such as one ten plus fourteen ones, and recognizes that the same number can be bundled in different ways. It converts such representations reliably into standard form.', 'B', 'B2.3'),
  ('C1.1a', 'Domäne C', 'emerald', 0, 'Additionsaufgaben bis 10 sicher lösen', 'Solving addition facts to 10 reliably', 'Das Kind ruft Additionsaufgaben bis zehn ohne Zehnerübergang direkt ab und nennt das Ergebnis, ohne nachzuzählen. Die Aufgaben sind als gespeicherte Zahlfakten verfügbar.', 'The child retrieves addition facts up to ten without crossing a ten directly and states the result without counting on. These tasks are available as stored number facts.', 'C', 'C1.1'),
  ('C1.1b', 'Domäne C', 'emerald', 0, 'Subtraktionsaufgaben bis 10 sicher lösen', 'Solving subtraction facts to 10 reliably', 'Das Kind ruft Subtraktionsaufgaben bis zehn direkt aus dem Gedächtnis ab und nennt das Ergebnis ohne nachzuzählen. Umkehraufgaben zur Addition werden dabei als Verbindung genutzt.', 'The child recalls subtraction facts up to ten directly from memory and states the result without counting back. Inverse tasks to addition are used as a connection.', 'C', 'C1.1'),
  ('C1.2', 'Domäne C', 'emerald', 0, 'Verdopplungsaufgaben sicher beherrschen', 'Mastering doubling facts', 'Das Kind beherrscht die Verdopplungsaufgaben im Zahlenraum bis zehn sicher und ruft die Ergebnisse automatisiert ab. Doppelte Mengen werden unmittelbar als solche erkannt.', 'The child masters doubling facts up to ten and recalls the results automatically. Double quantities are recognized immediately as such.', 'C', 'C1.2'),
  ('C1.3', 'Domäne C', 'emerald', 0, 'Halbierungsaufgaben sicher beherrschen', 'Mastering halving facts', 'Das Kind beherrscht die Halbierungen im Zahlenraum bis zehn und nutzt sie als Umkehrung der Verdopplungsaufgaben. Zu einer Zahl nennt es zuverlässig ihre Hälfte.', 'The child masters halving within ten and uses it as the inverse of doubling facts. For a given number it reliably states its half.', 'C', 'C1.3'),
  ('C2.1', 'Domäne C', 'emerald', 0, 'Addieren mit Zehnerübergang über Zerlegen', 'Adding across ten by decomposing', 'Das Kind löst Additionsaufgaben mit Zehnerübergang, indem es einen Summanden zerlegt und über den Zwischenschritt zur vollen Zehn gelangt. Das Teilschrittverfahren wird dabei bewusst als Weg gewählt.', 'The child solves addition tasks with a tens boundary by decomposing one addend and reaching a full ten as an intermediate step. The step-by-step procedure is chosen deliberately.', 'C', 'C2.1'),
  ('C2.2', 'Domäne C', 'emerald', 0, 'Verdopplungen als Stützaufgaben nutzen', 'Using doubles as anchor tasks', 'Das Kind nutzt bekannte Verdopplungen und Halbierungen als Stützpunkte für Aufgaben mit Zehnerübergang. Von der Verdopplungsaufgabe aus leitet es das Ergebnis der Nachbaraufgabe sicher ab.', 'The child uses known doubles and halves as anchor points for tasks that cross a ten. From the double it derives the result of the neighbouring task reliably.', 'C', 'C2.2'),
  ('C2.3', 'Domäne C', 'emerald', 0, 'Subtrahieren durch Ergänzen', 'Subtracting by adding on', 'Das Kind löst Subtraktionsaufgaben mit Zehnerübergang, indem es von der kleineren Zahl aus bis zum Ergebnis ergänzt. Es verzichtet dabei auf das mühsame rückwärts Zählen.', 'The child solves subtraction tasks across a ten by adding on from the smaller number to reach the result. It avoids laborious counting backward.', 'C', 'C2.3'),
  ('C3.1a', 'Domäne C', 'emerald', 0, 'Im Hunderterraum stellenweise addieren', 'Adding place-wise in the hundreds range', 'Das Kind addiert im Hunderterraum, indem es Zehner und Einer getrennt bearbeitet und die Teilergebnisse zusammenführt. Auch Aufgaben mit Übertrag gelingen über diesen Weg.', 'The child adds in the hundreds range by working on the tens and ones separately and combining the partial results. Tasks with a carry also work this way.', 'C', 'C3.1'),
  ('C3.1b', 'Domäne C', 'emerald', 0, 'Im Hunderterraum stellenweise subtrahieren', 'Subtracting place-wise in the hundreds range', 'Das Kind subtrahiert im Hunderterraum, indem es Zehner und Einer getrennt behandelt. Bei Aufgaben mit Zehnerunterschreitung borgt es einen Zehner und führt die Subtraktion zu Ende.', 'The child subtracts in the hundreds range by handling tens and ones separately. For tasks that cross a ten it borrows one ten and completes the subtraction.', 'C', 'C3.1'),
  ('C3.2', 'Domäne C', 'emerald', 0, 'Im Hunderterraum in Schritten rechnen', 'Calculating step by step in the hundreds range', 'Das Kind rechnet im Hunderterraum in mehreren Schritten und nutzt dabei den nächsten vollen Zehner als Zwischenziel. Das Auffüllen auf den Zehner erleichtert auch schwierige Aufgaben.', 'The child calculates in the hundreds range in several steps, using the next full ten as an intermediate target. Filling up to a ten also makes difficult tasks easier.', 'C', 'C3.2'),
  ('C3.3', 'Domäne C', 'emerald', 0, 'Mit Hilfsaufgaben rechnen', 'Calculating with supporting tasks', 'Das Kind nutzt bekannte Nachbar- und Ergänzungsaufgaben, um schwierige Aufgaben im Hunderterraum zu stützen. Vom Ergebnis der Hilfsaufgabe gelangt es über eine kleine Korrektur zum gesuchten Ergebnis.', 'The child uses known neighbour and complement tasks to support difficult calculations in the hundreds range. From the supporting task''s result it reaches the answer through a small correction.', 'C', 'C3.3'),
  ('C3.4a', 'Domäne C', 'emerald', 0, 'Im Hunderterraum zerlegen und addieren', 'Decomposing and adding in the hundreds range', 'Das Kind zerlegt Zahlen im Hunderterraum in rechnerisch günstige Teile, etwa in eine Verdopplung und eine kleine Korrektur. Aus den Teilschritten setzt es das Ergebnis sicher zusammen.', 'The child splits numbers in the hundreds range into computationally convenient parts, such as a double plus a small correction. It assembles the result reliably from the partial steps.', 'C', 'C3.4'),
  ('C3.4b', 'Domäne C', 'emerald', 0, 'Im Hunderterraum zerlegen und subtrahieren', 'Decomposing and subtracting in the hundreds range', 'Das Kind zerlegt bei Subtraktionsaufgaben im Hunderterraum den Subtrahenden in günstige Teile und subtrahiert schrittweise. Das Zerlegen erleichtert besonders Aufgaben, die eine Zehnergrenze überschreiten.', 'The child splits the subtrahend into convenient parts for subtraction tasks in the hundreds range and subtracts step by step. Decomposing especially helps tasks that cross a tens boundary.', 'C', 'C3.4'),
  ('C4.1', 'Domäne C', 'emerald', 0, 'Rechenstrategien bewusst auswählen', 'Choosing calculation strategies deliberately', 'Das Kind wählt die Rechenstrategie passend zu den gegebenen Zahlen und wechselt zwischen Verfahren, wenn das die Aufgabe erleichtert. Es begründet die gewählte Vorgehensweise.', 'The child chooses the calculation strategy to fit the given numbers and switches between procedures when that makes the task easier. It explains the approach it has chosen.', 'C', 'C4.1'),
  ('C4.2', 'Domäne C', 'emerald', 0, 'Umkehraufgaben zur Kontrolle nutzen', 'Using inverse tasks for checking', 'Das Kind nutzt die Umkehrbeziehung von Addition und Subtraktion, um Aufgaben zu vereinfachen oder Ergebnisse zu prüfen. Aus einer Plusaufgabe bildet es die zugehörige Minusaufgabe und umgekehrt.', 'The child uses the inverse relationship of addition and subtraction to simplify tasks or check results. From an addition it forms the matching subtraction and vice versa.', 'C', 'C4.2'),
  ('D1.1', 'Domäne D', 'violet', 0, 'Sachsituationen mathematisch erfassen', 'Understanding story situations mathematically', 'Das Kind entnimmt einer Sachsituation die relevanten Zahlen und die passende Operation und stellt die Situation als Rechenaufgabe dar. Es erkennt, welcher Teil der Geschichte für die Rechnung entscheidend ist.', 'The child extracts the relevant numbers and the right operation from a story situation and expresses it as a calculation. It recognizes which part of the story matters for the calculation.', 'D', 'D1.1'),
  ('D1.2', 'Domäne D', 'violet', 0, 'Die passende Rechenoperation erkennen', 'Recognizing the required operation', 'Das Kind erkennt in einer Sachsituation, welche Rechenoperation gefordert ist, und führt die zugehörige Rechnung aus. Es begründet die Wahl der Operation mit der Situation.', 'The child recognizes which operation a story situation requires and carries out the corresponding calculation. It justifies the choice of operation by the situation.', 'D', 'D1.2')
  on conflict (id) do nothing;

insert into public.diagnostics (id, slug, name_de, version, question_count) values
  ('00000000-0000-0000-0000-000000000002', 'cleanroom-v1', 'Numeris-Diagnostik v1 (Clean-Room)', 1, 60)
  on conflict (slug) do nothing;

-- Tier column (core vs deep-dive) and audio_asset (null for this bank; the
-- edge functions / dashboard reference it, so it must exist).
alter table public.diagnostic_questions
  add column if not exists tier text not null default 'core',
  add column if not exists audio_asset text;

-- core tier: 60 rows, question numbers 1..60
insert into public.diagnostic_questions (
  diagnostic_id, question_number, source_type, prompt_de, prompt_en, answer_format,
  correct_answer, if_wrong_practice_skills, if_wrong_skip, notes, tier, audio_asset)
values
  ('00000000-0000-0000-0000-000000000002', 1, 'text', '„Zähle von der Zahl 12 an weiter, bis zur Zahl 20."', 'Count on from the number 12 up to the number 20.', 'single', '"13, 14, 15, 16, 17, 18, 19, 20"'::jsonb, ARRAY['A1.1a'], NULL, 'easy; A1.1 Vorwärtszählen in ZR20/ZR100 vom beliebigen Startpunkt', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 2, 'text', '„Zähle von der Zahl 48 an weiter, bis zur Zahl 63."', 'Count on from the number 48 up to the number 63.', 'single', '"49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63"'::jsonb, ARRAY['A1.1b', 'A1.5'], NULL, 'medium; A1.1 Vorwärtszählen in ZR20/ZR100 vom beliebigen Startpunkt', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 3, 'text', '„Zähle von der Zahl 21 rückwärts, bis zur Zahl 16."', 'Count backwards from the number 21 down to the number 16.', 'single', '"20, 19, 18, 17, 16"'::jsonb, ARRAY['A1.2a'], NULL, 'easy; A1.2 Rückwärtszählen vom beliebigen Startpunkt', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 4, 'text', '„Zähle von der Zahl 59 rückwärts, bis zur Zahl 51."', 'Count backwards from the number 59 down to the number 51.', 'single', '"58, 57, 56, 55, 54, 53, 52, 51"'::jsonb, ARRAY['A1.2b'], NULL, 'medium; A1.2 Rückwärtszählen vom beliebigen Startpunkt', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 5, 'text', '„Zähle in Zweierschritten von der Zahl 26 an weiter. Nenne die nächsten vier Zahlen."', 'Count on in steps of two from the number 26. Name the next four numbers.', 'single', '"28, 30, 32, 34"'::jsonb, ARRAY['A1.3'], NULL, 'medium; A1.3 Zählen in Schritten (2er, 5er, 10er) vor- und rückwärts', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 6, 'text', '„Zähle in Fünferschritten rückwärts von der Zahl 45 an. Nenne die nächsten fünf Zahlen."', 'Count backwards in steps of five from the number 45. Name the next five numbers.', 'single', '"40, 35, 30, 25, 20"'::jsonb, ARRAY['A1.3'], NULL, 'hard; A1.3 Zählen in Schritten (2er, 5er, 10er) vor- und rückwärts', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 7, 'text', '„Welche Zahl kommt direkt vor der 37, und welche Zahl kommt direkt nach der 37?"', 'Which number comes directly before 37, and which number comes directly after 37?', 'single', '"36, 38"'::jsonb, ARRAY['A1.4', 'A1.1b'], NULL, 'easy; A1.4 Vorgänger/Nachfolger bestimmen', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 8, 'text', '„Zähle von der 17 an weiter, ohne abzubrechen, bis zur 23."', 'Count on from 17 without stopping until you reach 23.', 'single', '"18, 19, 20, 21, 22, 23"'::jsonb, ARRAY['A1.5', 'A1.1a'], NULL, 'medium; A1.5 Zählen über den Zehnerübergang hinweg', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 9, 'image', '„Gleich erscheint für einen kurzen Moment ein Rechenrahmen. Merke dir genau, wie viele Perlen du siehst. Wie viele Perlen waren es?“', 'A counting frame will appear for a short moment. Remember exactly how many beads you see. How many beads were there?', 'single', '"4"'::jsonb, ARRAY['A2.1', 'A1.1a'], NULL, 'Visual-ID: A2.1-01 | easy; A2.1 Simultanerfassung (Subitizing) bis 4–5 — das Kind erfasst kleine Mengen bis etwa vier oder fünf unmittelbar und zuverlässig, ohne sie einzeln abzuzählen.', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 10, 'image', '„Hier steht ein Zehnerfeld. Einige Felder sind gefüllt. Du darfst so lange schauen, wie du möchtest. Wie viele Felder sind gefüllt?“', 'Here is a ten-frame. Some boxes are filled. You may look as long as you like. How many boxes are filled?', 'single', '"6"'::jsonb, ARRAY['A2.2', 'A2.1'], NULL, 'Visual-ID: A2.2-01 | easy; A2.2 Strukturierte Anzahlerfassung bis 10 — das Kind erkennt Mengen bis zehn anhand bekannter Strukturen wie Fünfer- oder Zweiergruppierungen, Zehnerfeldern oder Fingerbildern.', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 11, 'image', '„Du siehst zwei Hände. Einige Finger sind ausgestreckt. Wie viele Finger sind es insgesamt?“', 'You see two hands. Some fingers are stretched out. How many fingers are there in total?', 'single', '"8"'::jsonb, ARRAY['A2.2', 'A2.1'], NULL, 'Visual-ID: A2.2-02 | medium; A2.2 Strukturierte Anzahlerfassung bis 10 — das Kind erkennt Mengen bis zehn anhand bekannter Strukturen wie Fünfer- oder Zweiergruppierungen, Zehnerfeldern oder Fingerbildern.', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 12, 'image', '„Links und rechts siehst du je ein Zehnerfeld. Wo sind mehr Felder gefüllt — links oder rechts?“', 'On the left and on the right you see a ten-frame. Where are more boxes filled — left or right?', 'single', '"rechts"'::jsonb, ARRAY['A2.3', 'A2.2'], NULL, 'Visual-ID: A2.3-01 | medium; A2.3 Anzahlvergleich / mehr-weniger — das Kind vergleicht Mengen und bestimmt zuverlässig, welche Menge größer beziehungsweise kleiner ist, ohne sie abzählen zu müssen.', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 13, 'text', '"In der Dose sind 6 Murmeln. 4 Murmeln sind rot, die anderen sind blau. Wie viele Murmeln sind blau?"', 'There are 6 marbles in the jar. 4 marbles are red, the others are blue. How many marbles are blue?', 'single', '"2"'::jsonb, ARRAY['A3.1', 'A2.2'], NULL, 'easy; A3.1 Teil-Teil-Ganzes in ZR10', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 14, 'text', '"Welche Zahl fehlt? 10 = 3 + ___"', 'Which number is missing? 10 = 3 + ___', 'single', '"7"'::jsonb, ARRAY['A3.1', 'A3.3'], NULL, 'medium; A3.1 Teil-Teil-Ganzes in ZR10', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 15, 'text', '"Lena hat 6 rote und 4 blaue Perlen. Wie viele Perlen hat Lena zusammen?"', 'Lena has 6 red and 4 blue beads. How many beads does Lena have altogether?', 'single', '"10"'::jsonb, ARRAY['A3.1', 'A3.3'], NULL, 'medium; A3.1 Teil-Teil-Ganzes in ZR10', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 16, 'text', '"Finde drei verschiedene Zerlegungen von 8. Schreib sie so auf: 8 = ___ + ___."', 'Find three different decompositions of 8. Write them like this: 8 = ___ + ___.', 'multiple', '"Drei verschiedene Zerlegungen der 8 in zwei natürliche Zahlen, z. B. 8 = 1 + 7, 8 = 2 + 6, 8 = 3 + 5 (oder 8 = 4 + 4)."'::jsonb, ARRAY['A3.2', 'A3.1'], NULL, 'medium; A3.2 Zerlegungen einer Zahl flexibel finden', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 17, 'text', '"Paul weiß: 8 = 5 + 3. Damit weiß er auch: 8 = 3 + ___. Welche Zahl fehlt?"', 'Paul knows: 8 = 5 + 3. That tells him: 8 = 3 + ___. Which number is missing?', 'single', '"5"'::jsonb, ARRAY['A3.2', 'A3.1'], NULL, 'medium; A3.2 Zerlegungen einer Zahl flexibel finden', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 18, 'text', '"Finde alle Zerlegungen von 10 in zwei Zahlen. Schreib jede Zerlegung genau einmal auf."', 'Find all decompositions of 10 into two numbers. Write each decomposition exactly once.', 'multiple', '"Vollständige Menge: 10 = 1 + 9, 10 = 2 + 8, 10 = 3 + 7, 10 = 4 + 6, 10 = 5 + 5."'::jsonb, ARRAY['A3.2', 'A3.1'], NULL, 'hard; A3.2 Zerlegungen einer Zahl flexibel finden', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 19, 'text', '"Kim kennt die Zahl 4. Welche Zahl ist doppelt so groß wie die 4?"', 'Kim knows the number 4. Which number is twice as large as 4?', 'single', '"8"'::jsonb, ARRAY['A3.3', 'A3.1'], NULL, 'easy; A3.3 Zahlbeziehungen (Verdopplungen, Nachbarzahlen)', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 20, 'text', '"Tim weiß: 4 + 4 = 8. Wie viel ist dann 4 + 5?"', 'Tim knows: 4 + 4 = 8. What is 4 + 5 then?', 'single', '"9"'::jsonb, ARRAY['A3.3', 'A3.1'], NULL, 'medium; A3.3 Zahlbeziehungen (Verdopplungen, Nachbarzahlen)', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 21, 'text', '»Sieh dir die Zahl an. Die Zahl ist 58. Wie viele Zehner hat die Zahl 58? Und wie viele Einer hat die Zahl 58?«', 'Look at the number. The number is 58. How many tens does 58 have? And how many ones does 58 have?', 'single', '"5 Zehner, 8 Einer."'::jsonb, ARRAY['B1.1', 'B1.2', 'B2.1'], NULL, 'easy; B1.1 Zehner und Einer in zweistelliger Zahl erkennen', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 22, 'image', '»Hier liegen Stäbchen. Einige sind zu Zehnern gebündelt. Zähle zuerst die Bündel, dann die einzelnen Stäbchen. Wie heißt die Zahl, die hier dargestellt ist?«', 'Here are sticks. Some are bundled in tens. Count the bundles first, then the single sticks. What number is shown here?', 'single', '"34."'::jsonb, ARRAY['B1.2', 'B1.1', 'A2.2'], NULL, 'Visual-ID: B1.2-01 | medium; B1.2 Bündelung von Einzelobjekten zu Zehnern', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 23, 'image', '»Hier liegen 3 gebündelte Zehner und 11 einzelne Stäbchen. Wie viele Stäbchen sind das zusammen? Und wenn du neu bündelst: Wie viele Zehner und wie viele Einer sind es dann?«', 'Here are 3 bundles of ten and 11 single sticks. How many sticks is that altogether? And if you bundle again: how many tens and how many ones are there then?', 'single', '"41 Stäbchen insgesamt; bei neuem Bündeln 4 Zehner und 1 Einer."'::jsonb, ARRAY['B1.2', 'B1.3', 'B2.3'], NULL, 'Visual-ID: B1.2-02 | hard; B1.2 Bündelung von Einzelobjekten zu Zehnern', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 24, 'image', '»Hier liegen 13 Stäbchen: ein Zehnerbündel und 3 einzelne Stäbchen. Öffne das Bündel, sodass lauter einzelne Stäbchen da liegen. Wie viele einzelne Stäbchen hast du dann?«', 'Here lie 13 sticks: one bundle of ten and 3 single sticks. Open the bundle so that only single sticks are left. How many single sticks do you have then?', 'single', '"13 einzelne Stäbchen."'::jsonb, ARRAY['B1.3', 'B1.1', 'B2.3'], NULL, 'Visual-ID: B1.3-01 | medium; B1.3 Entbündelung eines Zehners', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 25, 'image', '»Hier ist eine Stellenwerttafel mit zwei Spalten: Z für Zehner und E für Einer. Trage die Zahl 47 ein. Schreibe die Zehner in die Z-Spalte und die Einer in die E-Spalte.«', 'Here is a place-value table with two columns: Z for tens and E for ones. Enter the number 47. Write the tens in the Z column and the ones in the E column.', 'single', '"Z-Spalte: 4, E-Spalte: 7."'::jsonb, ARRAY['B2.1', 'B1.1', 'B2.3'], NULL, 'Visual-ID: B2.1-01 | easy; B2.1 Standardform und Stellenwerttafel', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 26, 'image', '»In dieser Stellenwerttafel steht in der Z-Spalte eine 6 und in der E-Spalte eine 0. Schreibe die Zahl auf, die in der Tafel steht.«', 'In this place-value table there is a 6 in the tens column and a 0 in the ones column. Write down the number that is in the table.', 'single', '"60."'::jsonb, ARRAY['B2.1', 'B1.1', 'A1.4'], NULL, 'Visual-ID: B2.1-02 | medium; B2.1 Standardform und Stellenwerttafel', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 27, 'image', '»Dieser Zahlenstrahl geht von 0 bis 100. Hier steht 0, hier steht 50, hier steht 100. Der Pfeil zeigt auf eine Stelle. Wie heißt die Zahl, auf die der Pfeil zeigt?«', 'This number line goes from 0 to 100. Here is 0, here is 50, here is 100. The arrow points to a position. What is the number the arrow points to?', 'single', '"80."'::jsonb, ARRAY['B2.2', 'B1.1', 'A1.5'], NULL, 'Visual-ID: B2.2-01 | medium; B2.2 Zahlen am Zahlenstrahl verorten', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 28, 'text', '»Lies diese Zahl genau: 1 Z + 14 E. Das heißt: 1 Zehner und 14 Einer. Wie heißt die Zahl?«', 'Read this number carefully: 1 Z + 14 E. That means: 1 ten and 14 ones. What is the number?', 'single', '"24."'::jsonb, ARRAY['B2.3', 'B1.2', 'B1.3'], NULL, 'hard; B2.3 Zahlen in nicht-standardisierter Form (z. B. »1 Z + 14 E«)', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 29, 'text', '"Wie viel ist 3 plus 4?"', 'How much is 3 plus 4?', 'single', '"7"'::jsonb, ARRAY['C1.1a', 'A3.1', 'A3.3'], NULL, 'easy; C1.1 Aufgaben ohne Zehnerübergang ZR10 automatisiert abrufbar', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 30, 'text', '"Wie viel ist 6 minus 6?"', 'How much is 6 minus 6?', 'single', '"0"'::jsonb, ARRAY['C1.1b', 'A3.1', 'A1.2a'], NULL, 'easy; C1.1 Aufgaben ohne Zehnerübergang ZR10 automatisiert abrufbar', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 31, 'text', '"Was ergibt 2 plus 8?"', 'What is 2 plus 8?', 'single', '"10"'::jsonb, ARRAY['C1.1a', 'A3.2', 'A3.1'], NULL, 'medium; C1.1 Aufgaben ohne Zehnerübergang ZR10 automatisiert abrufbar', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 32, 'text', '"Wie viel sind 10 minus 4?"', 'How much is 10 minus 4?', 'single', '"6"'::jsonb, ARRAY['C1.1b', 'A3.2', 'A3.1'], NULL, 'medium; C1.1 Aufgaben ohne Zehnerübergang ZR10 automatisiert abrufbar', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 33, 'text', '"Wie viel ist 4 plus 4?"', 'How much is 4 plus 4?', 'single', '"8"'::jsonb, ARRAY['C1.2', 'C1.1a', 'A3.3'], NULL, 'easy; C1.2 Verdopplungsaufgaben automatisiert', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 34, 'text', '"Wie viel ist 5 plus 5?"', 'How much is 5 plus 5?', 'single', '"10"'::jsonb, ARRAY['C1.2', 'A3.2', 'C1.1a'], NULL, 'medium; C1.2 Verdopplungsaufgaben automatisiert', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 35, 'text', '"Welche Zahl ist halb so groß wie 6?"', 'Which number is half as large as 6?', 'single', '"3"'::jsonb, ARRAY['C1.3', 'C1.2', 'A3.3'], NULL, 'easy; C1.3 Halbierungsaufgaben automatisiert', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 36, 'text', '"Welche Zahl ist halb so groß wie 10?"', 'Which number is half as large as 10?', 'single', '"5"'::jsonb, ARRAY['C1.3', 'C1.2', 'A3.2'], NULL, 'medium; C1.3 Halbierungsaufgaben automatisiert', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 37, 'text', '"Wie viel ist 7 plus 6?"', 'How much is 7 plus 6?', 'single', '"13"'::jsonb, ARRAY['C2.1', 'A3.1', 'C1.1a'], NULL, 'medium; C2.1 Zerlegungsstrategien (Teilschritt-Verfahren) ZR20 mit Zehnerübergang', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 38, 'text', '"Wie viel ist 8 plus 5?"', 'How much is 8 plus 5?', 'single', '"13"'::jsonb, ARRAY['C2.1', 'A3.1', 'A3.2'], NULL, 'medium; C2.1 Zerlegungsstrategien (Teilschritt-Verfahren) ZR20 mit Zehnerübergang', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 39, 'text', '"Wie viel ist 9 plus 7?"', 'How much is 9 plus 7?', 'single', '"16"'::jsonb, ARRAY['C2.1', 'A3.1', 'A3.2'], NULL, 'hard; C2.1 Zerlegungsstrategien (Teilschritt-Verfahren) ZR20 mit Zehnerübergang', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 40, 'text', '"Wie viel ist 8 plus 7?"', 'How much is 8 plus 7?', 'single', '"15"'::jsonb, ARRAY['C2.2', 'C1.2', 'A3.3'], NULL, 'medium; C2.2 Verdopplung/Halbierung als Stützpunkt (ZR20 mit Zehnerübergang)', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 41, 'text', '"Wie viel ist 9 plus 8?"', 'How much is 9 plus 8?', 'single', '"17"'::jsonb, ARRAY['C2.2', 'C1.2', 'C2.1'], NULL, 'hard; C2.2 Verdopplung/Halbierung als Stützpunkt (ZR20 mit Zehnerübergang)', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 42, 'text', '"Wie viel ist 13 minus 8?"', 'How much is 13 minus 8?', 'single', '"5"'::jsonb, ARRAY['C2.3', 'C2.1', 'C1.1b'], NULL, 'medium; C2.3 Ergänzen statt Abziehen bei Subtraktion (ZR20 mit Zehnerübergang)', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 43, 'text', '"Wie viel ist 12 minus 9?"', 'How much is 12 minus 9?', 'single', '"3"'::jsonb, ARRAY['C2.3', 'C2.1', 'C1.1b'], NULL, 'medium; C2.3 Ergänzen statt Abziehen bei Subtraktion (ZR20 mit Zehnerübergang)', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 44, 'text', '"Wie viel ist 15 minus 6?"', 'How much is 15 minus 6?', 'single', '"9"'::jsonb, ARRAY['C2.3', 'C2.1', 'A3.2'], NULL, 'hard; C2.3 Ergänzen statt Abziehen bei Subtraktion (ZR20 mit Zehnerübergang)', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 45, 'text', '»Rechne 34 + 28. In der Tabelle stehen Zehner und Einer. Die Zahl 34 hat 3 Zehner und 4 Einer. Die Zahl 28 hat 2 Zehner und 8 Einer. Trage ein: Wie viele Zehner haben beide Zahlen zusammen? Wie viele Einer haben beide Zahlen zusammen? Rechne jetzt alles zusammen und schreibe das Ergebnis auf.«', 'Calculate 34 + 28. In the table are the tens and the ones. The number 34 has 3 tens and 4 ones. The number 28 has 2 tens and 8 ones. Enter: How many tens do both numbers have together? How many ones do both numbers have together? Now add everything up and write down the result.', 'single', '"5 Zehner und 12 Einer; die 12 Einer sind 1 Zehner und 2 Einer; zusammen 6 Zehner und 2 Einer = 62. Finale Antwort: 62."'::jsonb, ARRAY['C3.1a', 'C2.1', 'B1.1'], NULL, 'medium; C3.1 Stellenweises Rechnen (Z ± Z, E ± E) — »Stellenweises Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 46, 'text', '»Rechne 57 − 19. Zerlege: 57 hat 5 Zehner und 7 Einer. 19 hat 1 Zehner und 9 Einer. Rechne zuerst die Zehner. Bei den Einern musst du einen Zehner auflösen. Erkläre, was du bei den Einern machst. Rechne dann 57 − 19 aus und trage das Ergebnis ein.«', 'Calculate 57 − 19. Split: 57 has 5 tens and 7 ones. 19 has 1 ten and 9 ones. First subtract the tens. With the ones you have to unbundle a ten. Explain what you do with the ones. Then calculate 57 − 19 and enter the result.', 'single', '"4 Zehner, 17 − 9 = 8 Einer → 38. Finale Antwort: 38."'::jsonb, ARRAY['C3.1b', 'C2.1', 'B1.3'], NULL, 'medium; C3.1 Stellenweises Rechnen (Z ± Z, E ± E) — »Stellenweises Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 47, 'text', '»Rechne 84 − 26. Zerlege 84 in Zehner und Einer. Zerlege 26 in Zehner und Einer. Rechne Zehner minus Zehner und Einer minus Einer. Was ist bei den Einern besonders? Wähle aus, wie du die Einer gerechnet hast, und rechne 84 − 26 aus.«', 'Calculate 84 − 26. Split 84 into tens and ones. Split 26 into tens and ones. Subtract tens minus tens and ones minus ones. What is special about the ones? Choose how you calculated the ones and calculate 84 − 26.', 'single', '"7 Zehner, 14 − 6 = 8 Einer → 58. Finale Antwort: 58."'::jsonb, ARRAY['C3.1b', 'B1.3', 'C3.4b'], NULL, 'hard; C3.1 Stellenweises Rechnen (Z ± Z, E ± E) — »Stellenweises Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 48, 'text', '»Rechne 26 + 35 in Schritten. Wie viel fehlt der 26 bis zum nächsten Zehner? Rechne: 26 + 4 = __. Wenn du die 4 von der 35 wegnimmst, wie viel bleibt von der 35 übrig? Rechne dann: 30 + 31 = __. Wie viel ist 26 + 35?«', 'Calculate 26 + 35 in steps. How much is missing from 26 to reach the next ten? Calculate: 26 + 4 = __. If you take the 4 away from 35, how much of 35 is left? Then calculate: 30 + 31 = __. How much is 26 + 35?', 'single', '"30 (26 + 4); 31 (35 − 4); 61 (30 + 31). Finale Antwort: 61."'::jsonb, ARRAY['C3.2', 'C3.1a', 'C2.3'], NULL, 'medium; C3.2 Schrittweises Rechnen (Auffüllen zum Zehner) — »Schrittweises Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 49, 'text', '»Rechne 63 − 28 in Schritten. Erst ziehst du die Zehner ab: 63 − 20 = __. Dann ziehst du die Einer ab: 43 − 8 = __. Wie viel ist 63 − 28?«', 'Calculate 63 − 28 in steps. First subtract the tens: 63 − 20 = __. Then subtract the ones: 43 − 8 = __. How much is 63 − 28?', 'single', '"43; 35; 35."'::jsonb, ARRAY['C3.2', 'C2.3', 'C3.1b'], NULL, 'medium; C3.2 Schrittweises Rechnen (Auffüllen zum Zehner) — »Schrittweises Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 50, 'text', '»Rechne 67 + 28 in Schritten. Fülle zuerst bis zum nächsten Zehner auf: 67 + 3 = __. Von der 28 bleiben dann 25 übrig. Rechne jetzt: 70 + 25 = __. Wie viel ist 67 + 28?«', 'Calculate 67 + 28 in steps. First fill up to the next ten: 67 + 3 = __. Of the 28, 25 then remains. Now calculate: 70 + 25 = __. How much is 67 + 28?', 'single', '"70 (67 + 3); 95 (70 + 25). Finale Antwort: 95."'::jsonb, ARRAY['C3.2', 'C3.1a', 'C2.1'], NULL, 'hard; C3.2 Schrittweises Rechnen (Auffüllen zum Zehner) — »Schrittweises Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 51, 'text', '»Diese Aufgabe hilft dir: 20 + 50 = 70. Rechne damit: 21 + 50 = __. Erkläre kurz, wie dir die 20 + 50 geholfen hat.«', 'This task helps you: 20 + 50 = 70. Use it to calculate: 21 + 50 = __. Briefly explain how 20 + 50 helped you.', 'single', '"71."'::jsonb, ARRAY['C3.3', 'C3.1a', 'A3.3'], NULL, 'medium; C3.3 Hilfsaufgaben (Nachbaraufgaben, Ergänzen) — »Hilfsaufgaben«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 52, 'text', '»Du kennst zwei Nachbaraufgaben: 45 + 40 = 85 und 45 + 30 = 75. Rechne damit: 45 + 38 = __. Erkläre, wie du gerechnet hast.«', 'You know two neighbouring tasks: 45 + 40 = 85 and 45 + 30 = 75. Use them to calculate: 45 + 38 = __. Explain how you calculated.', 'single', '"83 (85 − 2 oder 75 + 8)."'::jsonb, ARRAY['C3.3', 'C3.1a', 'A3.3'], NULL, 'hard; C3.3 Hilfsaufgaben (Nachbaraufgaben, Ergänzen) — »Hilfsaufgaben«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 53, 'text', '»Rechne 37 + 38. Tipp: Die 37 und die 38 sind fast gleich groß. Rechne zuerst 38 + 38 = __ und nimm dann 1 weg. Wie viel ist 37 + 38?«', 'Calculate 37 + 38. Tip: 37 and 38 are almost the same size. First calculate 38 + 38 = __ and then take 1 away. How much is 37 + 38?', 'single', '"76; 75. Finale Antwort: 75."'::jsonb, ARRAY['C3.4a', 'C3.3', 'C1.2'], NULL, 'medium; C3.4 Zerlegungsstrategien im ZR100 — »Zerlegungsstrategien«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 54, 'text', '»Rechne 73 − 38. Zerlege die 38 günstig: Die 38 ist fast 40. Rechne 73 − 40 = __ und rechne dann 2 dazu. Wie viel ist 73 − 38? Erkläre deinen Weg.«', 'Calculate 73 − 38. Split the 38 conveniently: 38 is almost 40. Calculate 73 − 40 = __ and then add 2. How much is 73 − 38? Explain your way.', 'single', '"33 (73 − 40); 35 (33 + 2). Finale Antwort: 35."'::jsonb, ARRAY['C3.4b', 'C3.2', 'C2.3'], NULL, 'hard; C3.4 Zerlegungsstrategien im ZR100 — »Zerlegungsstrategien«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 55, 'text', '»Rechne 34 + 29. [Reaktionszeiterfassung von der Anzeige bis zur Antwort.] Danach: »Wie hast du gerechnet?« Wähle einen Weg: (a) Ich habe 30 dazugerechnet und dann 1 abgezogen. (b) Ich habe zuerst die Zehner und dann die Einer gerechnet. (c) Ich habe zuerst 20 dazugerechnet und dann 9. (d) Ich habe gezählt oder nachgezählt.«', 'Calculate 34 + 29. Then: ''How did you calculate?'' Choose a way: (a) I added 30 and then subtracted 1. (b) I calculated the tens first and then the ones. (c) I added 20 first and then 9. (d) I counted.', 'single', '"63; Strategieoption (a) gilt als flexibel passend, (b) und (c) als korrekt, aber weniger angepasst, (d) als nicht flexibel."'::jsonb, ARRAY['C4.1', 'C3.1a', 'C2.1'], NULL, 'medium; C4.1 Strategieauswahl abhängig von Zahlen — »Flexibles Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 56, 'text', '»Rechne 52 − 19. [Reaktionszeiterfassung von der Anzeige bis zur Antwort.] Danach: »Wie hast du gerechnet?« Wähle einen Weg: (a) Ich habe 20 abgezogen und 1 dazugezählt: 52 − 20 = 32, dann 32 + 1. (b) Ich habe erst die Zehner und dann die Einer abgezogen: 52 − 10 = 42, dann 42 − 9. (c) Ich habe von 19 bis 52 weitergerechnet. (d) Ich habe gezählt oder nachgezählt.«', 'Calculate 52 − 19. Then: ''How did you calculate?'' Choose a way: (a) I subtracted 20 and added 1: 52 − 20 = 32, then 32 + 1. (b) I subtracted the tens first and then the ones: 52 − 10 = 42, then 42 − 9. (c) I counted on from 19 to 52. (d) I counted.', 'single', '"33; Option (a) gilt als flexibel passend, (b) als korrekt, aber weniger angepasst, (c) als korrektes Ergänzen, (d) als nicht flexibel."'::jsonb, ARRAY['C4.1', 'C3.2', 'C2.3'], NULL, 'hard; C4.1 Strategieauswahl abhängig von Zahlen — »Flexibles Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 57, 'text', '»Wir wissen: 43 + 29 = 72. Rechne damit: 72 − 29 = __. Und rechne: 72 − 43 = __. [Reaktionszeiterfassung von der Anzeige bis zur ersten Antwort.] Danach: »Wie hast du gerechnet?« (a) Ich habe die Plusaufgabe umgedreht. (b) Ich habe einzeln abgezogen. (c) Ich habe gezählt.«', 'We know: 43 + 29 = 72. Use it: 72 − 29 = __. And calculate: 72 − 43 = __. Then: ''How did you calculate?'' (a) I turned the addition around. (b) I subtracted step by step. (c) I counted.', 'single', '"43; 29. Option (a) gilt als flexibel passend."'::jsonb, ARRAY['C4.2', 'C3.1b', 'C1.3'], NULL, 'medium; C4.2 Inverse Beziehung Addition/Subtraktion nutzen — »Flexibles Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 58, 'text', '»Rechne 83 − 47. Tipp: Nutze die Umkehraufgabe. Welche Plusaufgabe passt zu 83 − 47? Rechne: 47 + __ = 83. Wie viel ist dann 83 − 47? [Reaktionszeiterfassung von der Anzeige bis zur ersten Antwort.] Danach: »Wie hast du gerechnet?« (a) Ich habe von 47 auf 83 ergänzt. (b) Ich habe die Umkehraufgabe benutzt. (c) Ich habe schrittweise abgezogen. (d) Ich habe gezählt.«', 'Calculate 83 − 47. Tip: use the inverse task. Which addition fits 83 − 47? Calculate: 47 + __ = 83. What is 83 − 47 then? Then: ''How did you calculate?'' (a) I added on from 47 to 83. (b) I used the inverse task. (c) I subtracted step by step. (d) I counted.', 'single', '"47 + 36 = 83; 83 − 47 = 36. Option (a) oder (b) gilt als flexibel passend."'::jsonb, ARRAY['C4.2', 'C3.4b', 'C2.3'], NULL, 'hard; C4.2 Inverse Beziehung Addition/Subtraktion nutzen — »Flexibles Rechnen«', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 59, 'text', '„Beim Schwimmunterricht im Hallenbad schwimmen die Kinder Bahnen. Luna schwimmt in der ersten Übung 8 Bahnen. Nach der Pause schwimmt sie noch 5 Bahnen. Wie viele Bahnen hat Luna insgesamt geschwommen? Schreibe die passende Rechnung auf und rechne sie aus."', 'In swimming class the children swim laps in the pool. In the first exercise Luna swims 8 laps. After the break she swims 5 more laps. How many laps did Luna swim in total? Write down the matching calculation and work it out.', 'single', '"8 + 5 = 13"'::jsonb, ARRAY['D1.1', 'C2.1', 'C1.1a'], NULL, 'medium; D1.1 Mathematisierung von Alltagskontexten', 'core', NULL),
  ('00000000-0000-0000-0000-000000000002', 60, 'text', '„Im Schulgarten haben die Kinder der 2b Bohnen gesät. Heute Morgen zählt Leo 9 Bohnenpflanzen in seinem Beet. Am Nachmittag sieht er: Es sind 4 Pflanzen mehr. Wie viele Bohnenpflanzen stehen jetzt in Leos Beet? Kreuze die passende Rechnung an und rechne sie aus:  9 + 4  ·  9 − 4  ·  4 − 9."', 'In the school garden class 2b sowed beans. This morning Leo counts 9 bean plants in his bed. In the afternoon he sees: there are 4 more plants. How many bean plants are in Leo''s bed now? Tick the matching calculation and work it out: 9 + 4 · 9 − 4 · 4 − 9.', 'multiple', '"9 + 4, 13"'::jsonb, ARRAY['D1.2', 'C2.1', 'C1.1a'], NULL, 'medium; D1.2 Erkennen der Rechenoperation', 'core', NULL)
  on conflict (diagnostic_id, question_number) do nothing;

-- deepdive tier: 32 rows, question numbers 61..92
insert into public.diagnostic_questions (
  diagnostic_id, question_number, source_type, prompt_de, prompt_en, answer_format,
  correct_answer, if_wrong_practice_skills, if_wrong_skip, notes, tier, audio_asset)
values
  ('00000000-0000-0000-0000-000000000002', 61, 'text', '„Zähle in Zehnerschritten von der Zahl 47 an weiter. Nenne die nächsten vier Zahlen.“', 'Count on in steps of ten from the number 47. Name the next four numbers.', 'single', '"57, 67, 77, 87"'::jsonb, ARRAY['A1.3', 'A1.1b'], NULL, 'medium; A1.3 Zählen in Schritten (2er, 5er, 10er) vor- und rückwärts — Zehnerschritte vorwärts', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 62, 'text', '„Zähle vorwärts von 86 bis 94.“', 'Count forward from 86 to 94.', 'single', '"86, 87, 88, 89, 90, 91, 92, 93, 94"'::jsonb, ARRAY['A1.5', 'A1.1b'], NULL, 'medium; A1.5 Zählen über den Zehnerübergang hinweg — vorwärts', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 63, 'text', '„Zähle rückwärts in Fünferschritten von 60 bis 35.“', 'Count backwards in steps of five from 60 to 35.', 'single', '"60, 55, 50, 45, 40, 35"'::jsonb, ARRAY['A1.3', 'A1.2b'], NULL, 'hard; A1.3 Zählen in Schritten (2er, 5er, 10er) vor- und rückwärts — Fünferschritte rückwärts', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 64, 'image', '„Hier ist ein Zehnerfeld. Einige Felder sind gefüllt. Du darfst so lange schauen, wie du möchtest. Wie viele Felder sind gefüllt?“', 'Here is a ten-frame. Some boxes are filled. You may look as long as you like. How many boxes are filled?', 'single', '"7"'::jsonb, ARRAY['A2.2', 'A2.1'], NULL, 'Visual-ID: DDA-04 | medium; A2.2 Strukturierte Anzahlerfassung bis 10 — Zehnerfeld 5+2', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 65, 'image', '„Hier siehst du ein Rechenbrett mit zwei Stäben. Einige Perlen sind nach links geschoben. Wie viele Perlen sind links?“', 'Here you see a counting board with two rods. Some beads are pushed to the left. How many beads are on the left?', 'single', '"9"'::jsonb, ARRAY['A2.2', 'A2.1'], NULL, 'Visual-ID: DDA-05 | medium; A2.2 Strukturierte Anzahlerfassung bis 10 — Rekenrek 5+4', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 66, 'image', '„Hier liegen zwei Rechenbretter. Auf welchem Brett sind mehr Perlen? Wie viele mehr?“', 'Here lie two counting boards. On which board are more beads? How many more?', 'single', '"Links sind mehr Perlen; es sind 3 mehr."'::jsonb, ARRAY['A2.3', 'A2.2'], NULL, 'Visual-ID: DDA-06 | hard; A2.3 Anzahlvergleich / mehr-weniger — mit strukturierter Darstellung', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 67, 'text', '„Finde drei verschiedene Zerlegungen der Zahl 9. Schreib sie so auf: 9 = ___ + ___.“', 'Find three different decompositions of the number 9. Write them like this: 9 = ___ + ___.', 'multiple', '"Drei verschiedene Zerlegungen der 9 in zwei natürliche Zahlen, z. B. 9 = 1 + 8, 9 = 2 + 7, 9 = 3 + 6 (oder 9 = 4 + 5)."'::jsonb, ARRAY['A3.2', 'A3.1'], NULL, 'medium; A3.2 Zerlegungen einer Zahl flexibel finden — Zerlegungen der 9', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 68, 'text', '„Die Zahl 7 besteht aus 3 und noch einer Zahl. Wie heißt die andere Zahl?“', 'The number 7 consists of 3 and another number. What is the other number?', 'single', '"4"'::jsonb, ARRAY['A3.1', 'A3.2'], NULL, 'medium; A3.1 Teil-Teil-Ganzes in ZR10 — Ergänzen zum Ganzen', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 69, 'text', '„Du weißt: 5 und 5 sind 10. Wie viel sind dann 5 und 6? Erkläre kurz, wie du darauf kommst.“', 'You know: 5 and 5 are 10. What are 5 and 6 then? Briefly explain how you get it.', 'single', '"11"'::jsonb, ARRAY['A3.3', 'C1.2'], NULL, 'hard; A3.3 Zahlbeziehungen (Verdopplungen, Nachbarzahlen) — Nachbaraufgabe 5+5 → 5+6', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 70, 'text', '„Wenn du die Zahl 6 verdoppelst, welche Zahl bekommst du? Und welches ist dann die Hälfte von 12?“', 'If you double the number 6, which number do you get? And what is half of 12 then?', 'single', '"12 und 6."'::jsonb, ARRAY['A3.3', 'C1.2', 'C1.3'], NULL, 'hard; A3.3 Zahlbeziehungen (Verdopplungen, Halbierungen) — Doppeltes und Hälfte als Umkehrung', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 71, 'image', '„Hier liegen Stäbchen. Einige sind zu Zehnern gebündelt. Zähle zuerst die Bündel, dann die einzelnen Stäbchen. Wie heißt die Zahl, die hier dargestellt ist?“', 'Here are sticks. Some are bundled in tens. Count the bundles first, then the single sticks. What number is shown here?', 'single', '"56."'::jsonb, ARRAY['B1.2', 'B1.1', 'A2.2'], NULL, 'Visual-ID: DDB-01 | medium; B1.2 Bündelung von Einzelobjekten zu Zehnern — 5 Zehnerbündel und 6 Einer', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 72, 'image', '„Die Zahl 25 ist gelegt als 2 Zehner und 5 Einer. Tausche einen Zehner in zehn einzelne Stäbchen. Wie viele Zehner und wie viele Einer hast du jetzt? Trage es ein.“', 'The number 25 is laid out as 2 tens and 5 ones. Exchange one ten for ten single sticks. How many tens and how many ones do you have now? Enter it.', 'single', '"1 Zehner und 15 Einer."'::jsonb, ARRAY['B1.3', 'B2.3'], NULL, 'Visual-ID: DDB-02 | hard; B1.3 Entbündelung eines Zehners — Umformung in nicht-standardisierte Bündelung', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 73, 'text', '„Hier steht die Zahl 60. Wie viele Zehner hat sie? Und wie viele Einer?“', 'Here is the number 60. How many tens does it have? And how many ones?', 'single', '"6 Zehner und 0 Einer."'::jsonb, ARRAY['B1.1', 'B2.1'], NULL, 'hard; B1.1 Zehner und Einer in zweistelliger Zahl erkennen — Nullstelle als Grenzfall', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 74, 'image', '„In dieser Stellenwerttafel stehen die Zehner und die Einer. Die Tafel zeigt links die Zehner und rechts die Einer. Wie heißt die Zahl?“', 'In this place-value table are the tens and the ones. The table shows the tens on the left and the ones on the right. What is the number?', 'single', '"58."'::jsonb, ARRAY['B2.1', 'B1.1'], NULL, 'Visual-ID: DDB-04 | medium; B2.1 Standardform und Stellenwerttafel — Lesen aus der Tafel', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 75, 'image', '„Hier ist ein Zahlenstrahl von 0 bis 100. Markiere die Zahl 75 auf dem Zahlenstrahl.“', 'Here is a number line from 0 to 100. Mark the number 75 on the number line.', 'single', '"Markierung am Teilstrich 75."'::jsonb, ARRAY['B2.2', 'B2.1'], NULL, 'Visual-ID: DDB-05 | medium; B2.2 Zahlen am Zahlenstrahl verorten — 75 auf dem 0–100-Strahl', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 76, 'text', '„Ich sage dir gleich eine Zahl. Höre gut zu, ich sage sie nur einmal. Schreib die Zahl auf: Siebzig.“', 'I will say a number to you in a moment. Listen carefully, I say it only once. Write the number down: Seventy.', 'single', '"70."'::jsonb, ARRAY['B2.1', 'B1.1'], NULL, 'hard; B2.1 Standardform und Stellenwerttafel — auditive Zahldarstellung (Zahlendiktat in eigener Form)', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 77, 'text', '„Wie viel ist 9 + 5? Nenne das Ergebnis.“', 'How much is 9 + 5? State the result.', 'single', '"14."'::jsonb, ARRAY['C2.1', 'A3.1', 'A3.2'], NULL, 'medium; C2.1 Zerlegungsstrategien (Teilschritt-Verfahren) — 9 + 5 im ZR20 mit Zehnerübergang', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 78, 'text', '„Wie viel ist 14 − 8? Nenne das Ergebnis.“', 'How much is 14 − 8? State the result.', 'single', '"6."'::jsonb, ARRAY['C2.3', 'C1.1b'], NULL, 'medium; C2.3 Ergänzen statt Abziehen bei Subtraktion — 14 − 8', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 79, 'text', '„Wie viel ist 7 + 8? Nenne das Ergebnis.“', 'How much is 7 + 8? State the result.', 'single', '"15."'::jsonb, ARRAY['C2.2', 'A3.3', 'C1.2'], NULL, 'hard; C2.2 Verdopplung/Halbierung als Stützpunkt — 7 + 8 als Nachbaraufgabe', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 80, 'text', '„Wie viel ist 16 − 9? Nenne das Ergebnis.“', 'How much is 16 − 9? State the result.', 'single', '"7."'::jsonb, ARRAY['C2.3', 'C1.1b'], NULL, 'hard; C2.3 Ergänzen statt Abziehen bei Subtraktion — 16 − 9', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 81, 'text', '„Wie viel ist 48 − 26? Nenne das Ergebnis.“', 'How much is 48 − 26? State the result.', 'single', '"22."'::jsonb, ARRAY['C3.1b', 'B1.1'], NULL, 'medium; C3.1 Stellenweises Rechnen (Z ± Z, E ± E) — 48 − 26', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 82, 'text', '„Wie viel ist 37 + 8? Nenne das Ergebnis.“', 'How much is 37 + 8? State the result.', 'single', '"45."'::jsonb, ARRAY['C3.2', 'A1.5'], NULL, 'medium; C3.2 Schrittweises Rechnen — 37 + 8 über die Zehnergrenze', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 83, 'text', '„Wie viel ist 38 + 27? Nenne das Ergebnis.“', 'How much is 38 + 27? State the result.', 'single', '"65."'::jsonb, ARRAY['C3.1a', 'C2.1'], NULL, 'hard; C3.1 Stellenweises Rechnen (Z ± Z, E ± E) — 38 + 27 mit Zehnerübertrag', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 84, 'text', '„Wie viel ist 62 − 7? Nenne das Ergebnis.“', 'How much is 62 − 7? State the result.', 'single', '"55."'::jsonb, ARRAY['C3.2', 'A1.5'], NULL, 'hard; C3.2 Schrittweises Rechnen — 62 − 7 über die Zehnergrenze', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 85, 'text', '„Wie viel ist 36 + 39? Nenne das Ergebnis.“', 'How much is 36 + 39? State the result.', 'single', '"75."'::jsonb, ARRAY['C3.3', 'C3.1a', 'C2.2'], NULL, 'hard; C3.3 Hilfsaufgaben (Nachbaraufgaben, Ergänzen) — 36 + 39 über die Nachbaraufgabe', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 86, 'text', '„Wie viel ist 54 − 28? Nenne das Ergebnis.“', 'How much is 54 − 28? State the result.', 'single', '"26."'::jsonb, ARRAY['C3.4b', 'B1.3', 'C2.1'], NULL, 'hard; C3.4 Zerlegungsstrategien — 54 − 28 über Entbündelung', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 87, 'text', '„Auf dem Schulfest sind 14 Kinder beim Schminken. 6 Kinder sind schon fertig. Wie viele Kinder warten noch? Schreibe nur die Rechnung auf, du brauchst nicht zu rechnen.“', 'At the school fair 14 children are getting their faces painted. 6 children are already finished. How many children are still waiting? Only write down the calculation, you do not need to work it out.', 'single', '"14 − 6"'::jsonb, ARRAY['D1.1', 'D1.2'], NULL, 'medium; D1.1 Mathematisierung von Alltagskontexten — Schulfest, Schminkstand', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 88, 'text', '„An der Garderobe der Klasse hängen 8 Jacken. 3 Jacken werden in der Pause abgeholt. Schreibe die Rechnung auf.“', '8 jackets are hanging in the class cloakroom. 3 jackets are picked up during break. Write down the calculation.', 'single', '"8 − 3"'::jsonb, ARRAY['D1.1', 'D1.2'], NULL, 'medium; D1.1 Mathematisierung von Alltagskontexten — Garderobe', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 89, 'text', '„Im Fahrradständer der Schule stehen 9 Fahrräder. In der Mittagspause kommen 4 Fahrräder dazu. Schreibe die Rechnung auf.“', '9 bicycles are standing in the school bike rack. At lunchtime 4 more bicycles are added. Write down the calculation.', 'single', '"9 + 4"'::jsonb, ARRAY['D1.1', 'C2.1'], NULL, 'hard; D1.1 Mathematisierung von Alltagskontexten — Fahrradständer', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 90, 'text', '„In der Pause spielen 6 Kinder am Klettergerüst und 5 Kinder an der Schaukel. Wie viele Kinder spielen zusammen?“', 'During break 6 children are playing on the climbing frame and 5 children on the swing. How many children are playing together?', 'single', '"11."'::jsonb, ARRAY['D1.2', 'D1.1'], NULL, 'medium; D1.2 Erkennen der Rechenoperation — Pausenhof, Klettergerüst und Schaukel', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 91, 'text', '„In der Klassenbücherei liegen 12 Bilderbücher im Regal. 4 Bücher werden ausgeliehen. Wie viele Bücher bleiben im Regal?“', '12 picture books are lying on the shelf in the class library. 4 books are borrowed. How many books stay on the shelf?', 'single', '"8."'::jsonb, ARRAY['D1.2', 'C1.1b'], NULL, 'medium; D1.2 Erkennen der Rechenoperation — Klassenbücherei', 'deepdive', NULL),
  ('00000000-0000-0000-0000-000000000002', 92, 'text', '„In Toms Turnbeutel sind 9 Springseile. In Annas Turnbeutel sind 7 Springseile. Wie viele Springseile haben beide zusammen?“', 'In Tom''s sports bag there are 9 skipping ropes. In Anna''s sports bag there are 7 skipping ropes. How many skipping ropes do they have together?', 'single', '"16."'::jsonb, ARRAY['D1.2', 'C2.1'], NULL, 'hard; D1.2 Erkennen der Rechenoperation — Turnbeutel mit Springseilen', 'deepdive', NULL)
  on conflict (diagnostic_id, question_number) do nothing;

-- Sanity anchors (informational):
--   select id, slug, version, question_count from public.diagnostics where slug = 'cleanroom-v1';
--   select count(*) from public.diagnostic_questions where diagnostic_id = '00000000-0000-0000-0000-000000000002' and tier = 'core';
--   select count(*) from public.diagnostic_questions where diagnostic_id = '00000000-0000-0000-0000-000000000002' and tier = 'deepdive';
--   select count(*) from public.skills where domain is not null;
